//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References.Mobile {

	[Persistent(@"Table_025")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class MobileErrors : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		SUTZ_2.Module.BO.References.Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public SUTZ_2.Module.BO.References.Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		[Size(30)]
		[Persistent(@"f003")]
		[DisplayName(@"Наименование")]
		[Delayed(false)]
		public string Description {
			get { return GetDelayedPropertyValue<string>("Description"); }
			set { SetDelayedPropertyValue<string>("Description", value); }
		}
		[Persistent(@"f004")]
		[DisplayName(@"Полное наименование")]
		[Delayed(false)]
		public string FullDescription {
			get { return GetDelayedPropertyValue<string>("FullDescription"); }
			set { SetDelayedPropertyValue<string>("FullDescription", value); }
		}
		Guid fidGUID;
		[Persistent(@"f005")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"IDD SUTZ")]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		string fCode;
		[Size(5)]
		[Persistent(@"f006")]
		[DisplayName(@"Код")]
		public string Code {
			get { return fCode; }
			set { SetPropertyValue<string>("Code", ref fCode, value); }
		}
		bool fIsEnable;
		[Persistent(@"f007")]
		[DisplayName(@"Включен")]
		public bool IsEnable {
			get { return fIsEnable; }
			set { SetPropertyValue<bool>("IsEnable", ref fIsEnable, value); }
		}
		bool fIsError;
		[Persistent(@"f008")]
		[DisplayName(@"Это ошибка")]
		public bool IsError {
			get { return fIsError; }
			set { SetPropertyValue<bool>("IsError", ref fIsError, value); }
		}
		bool fIsDone;
		[Persistent(@"f009")]
		[DisplayName(@"Выполнен")]
		public bool IsDone {
			get { return fIsDone; }
			set { SetPropertyValue<bool>("IsDone", ref fIsDone, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f010")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
