//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SUTZ_2.Module.BO.Documents
{

    [Persistent(@"Table_120")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class DocInvoiceOrder : BaseDocument
    {
        DateTime fExecutionDate;
        [Persistent(@"f050")]
        [DevExpress.Xpo.DisplayName(@"Дата исполнения")]
        public DateTime ExecutionDate
        {
            get { return fExecutionDate; }
            set { SetPropertyValue<DateTime>("ExecutionDate", ref fExecutionDate, value); }
        }
        SUTZ_2.Module.BO.References.Clients fClient;
        [Persistent(@"f051")]
        [DevExpress.Xpo.DisplayName(@"Клиент")]
        public SUTZ_2.Module.BO.References.Clients Client
        {
            get { return fClient; }
            set { SetPropertyValue<SUTZ_2.Module.BO.References.Clients>("Client", ref fClient, value); }
        }
        SUTZ_2.Module.BO.DocStatesASUInvoice fStatusASU;
        [Persistent(@"f052")]
        [DevExpress.Xpo.DisplayName(@"Статус АСУ")]
        public SUTZ_2.Module.BO.DocStatesASUInvoice StatusASU
        {
            get { return fStatusASU; }
            set { SetPropertyValue<SUTZ_2.Module.BO.DocStatesASUInvoice>("StatusASU", ref fStatusASU, value); }
        }
        bool fUnloaded;
        /// <summary>
        /// Документ выгружен в АСУ
        /// </summary>
        [Persistent(@"f053")]
        [DevExpress.Xpo.DisplayName(@"Выгружен")]
        public bool Unloaded
        {
            get { return fUnloaded; }
            set { SetPropertyValue<bool>("Unloaded", ref fUnloaded, value); }
        }
        bool fPrinted;
        [Persistent(@"f054")]
        [DevExpress.Xpo.DisplayName(@"Распечатан")]
        public bool Printed
        {
            get { return fPrinted; }
            set { SetPropertyValue<bool>("Printed", ref fPrinted, value); }
        }
        SUTZ_2.Module.BO.References.Warehouses fWarehouse;
        /// <summary>
        /// Склад-отправитель
        /// </summary>
        [Persistent(@"f055")]
        [DevExpress.Xpo.DisplayName(@"Склад")]
        public SUTZ_2.Module.BO.References.Warehouses Warehouse
        {
            get { return fWarehouse; }
            set { SetPropertyValue<SUTZ_2.Module.BO.References.Warehouses>("Warehouse", ref fWarehouse, value); }
        }
        bool fShipped;
        /// <summary>
        /// Товар отгружен
        /// </summary>
        [Persistent(@"f056")]
        [DevExpress.Xpo.DisplayName(@"Товар отгружен")]
        public bool Shipped
        {
            get { return fShipped; }
            set { SetPropertyValue<bool>("Shipped", ref fShipped, value); }
        }
        SUTZ_2.Module.BO.enDeliveryTypes fDeliveryType;
        [Persistent(@"f057")]
        [DevExpress.Xpo.DisplayName(@"Вид отправки")]
        public SUTZ_2.Module.BO.enDeliveryTypes DeliveryType
        {
            get { return fDeliveryType; }
            set { SetPropertyValue<SUTZ_2.Module.BO.enDeliveryTypes>("DeliveryType", ref fDeliveryType, value); }
        }
        SUTZ_2.Module.BO.References.ClientDivisions fClientDivision;
        [Persistent(@"f058")]
        [DevExpress.Xpo.DisplayName(@"Подразделение клиента")]
        public SUTZ_2.Module.BO.References.ClientDivisions ClientDivision
        {
            get { return fClientDivision; }
            set { SetPropertyValue<SUTZ_2.Module.BO.References.ClientDivisions>("ClientDivision", ref fClientDivision, value); }
        }
        SUTZ_2.Module.BO.References.ClientShops fClientShop;
        [Persistent(@"f059")]
        [DevExpress.Xpo.DisplayName(@"Магазин клиента")]
        public SUTZ_2.Module.BO.References.ClientShops ClientShop
        {
            get { return fClientShop; }
            set { SetPropertyValue<SUTZ_2.Module.BO.References.ClientShops>("ClientShop", ref fClientShop, value); }
        }
        [Association(@"DocListOfGoodsInvoiceOrderReferencesDocInvoiceOrder"), Aggregated]
        public XPCollection<DocInvoiceOrderGoods> DocListOfGoods { get { return GetCollection<DocInvoiceOrderGoods>("DocListOfGoods"); } }
    }

}
