//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SUTZ_2.Module.BO.Documents
{

    [Persistent(@"Table_150")]
    public partial class DocSpecRashoda : BaseDocument
    {
        SUTZ_2.Module.BO.References.StockRooms fStockRoomFrom;
        [Persistent(@"f050")]
        [DevExpress.Xpo.DisplayName(@"Кладовая-отправитель")]
        public SUTZ_2.Module.BO.References.StockRooms StockRoomFrom
        {
            get { return fStockRoomFrom; }
            set { SetPropertyValue<SUTZ_2.Module.BO.References.StockRooms>("StockRoomFrom", ref fStockRoomFrom, value); }
        }
        bool fOrderClosed;
        [Persistent(@"f051")]
        [DevExpress.Xpo.DisplayName(@"Заказ закрыт")]
        public bool OrderClosed
        {
            get { return fOrderClosed; }
            set { SetPropertyValue<bool>("OrderClosed", ref fOrderClosed, value); }
        }
        bool fTovarOtobran;
        [Persistent(@"f052")]
        [DevExpress.Xpo.DisplayName(@"Товар отобран")]
        public bool TovarOtobran
        {
            get { return fTovarOtobran; }
            set { SetPropertyValue<bool>("TovarOtobran", ref fTovarOtobran, value); }
        }
        bool fTovarPoluchen;
        [Persistent(@"f053")]
        [DevExpress.Xpo.DisplayName(@"Товар получен")]
        public bool TovarPoluchen
        {
            get { return fTovarPoluchen; }
            set { SetPropertyValue<bool>("TovarPoluchen", ref fTovarPoluchen, value); }
        }
        [Association(@"GeneralXpObject1ReferencesDocSpecRashoda"), Aggregated]
        public XPCollection<DocSpecRashodaGoods> DocListOfGoods { get { return GetCollection<DocSpecRashodaGoods>("DocListOfGoods"); } }
    }

}
