//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.Exchange.SUTZ1C_SUTZNET {

	public partial class NET_SUTZ_MobileWorkUsers : XPLiteObject {
		int frow_id;
		[Key(true)]
		public int row_id {
			get { return frow_id; }
			set { SetPropertyValue<int>("row_id", ref frow_id, value); }
		}
		NET_SUTZ_MobileWorkUnit fParentID;
		[Indexed(Name=@"Index_ParentID")]
		[Association(@"NET_SUTZ_MobileWorkUsersReferencesNET_SUTZ_MobileWorkUnit")]
		public NET_SUTZ_MobileWorkUnit ParentID {
			get { return fParentID; }
			set { SetPropertyValue<NET_SUTZ_MobileWorkUnit>("ParentID", ref fParentID, value); }
		}
		Guid fUser;
		[DisplayName(@"Пользователь")]
		public Guid User {
			get { return fUser; }
			set { SetPropertyValue<Guid>("User", ref fUser, value); }
		}
		DateTime fdTimeEnd;
		[DisplayName(@"Время завершения")]
		public DateTime dTimeEnd {
			get { return fdTimeEnd; }
			set { SetPropertyValue<DateTime>("dTimeEnd", ref fdTimeEnd, value); }
		}
		DateTime fdTimeStart;
		[DisplayName(@"Время начала")]
		public DateTime dTimeStart {
			get { return fdTimeStart; }
			set { SetPropertyValue<DateTime>("dTimeStart", ref fdTimeStart, value); }
		}
		Guid fMobileError;
		[DisplayName(@"Ошибка моб.сутз")]
		public Guid MobileError {
			get { return fMobileError; }
			set { SetPropertyValue<Guid>("MobileError", ref fMobileError, value); }
		}
		int fiddint;
		/// <summary>
		/// В этом поле будет выгружаться idd элемента в СУТЗ.NET, как идентификатор записи для поиска в СУТЗ 7.7 элемента по конкретному полю.
		/// </summary>
		[DisplayName(@"idd int")]
		public int iddint {
			get { return fiddint; }
			set { SetPropertyValue<int>("iddint", ref fiddint, value); }
		}
	}

}
