//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.Exchange.SUTZ1C_SUTZNET {

	public partial class NET_SUTZ_MobileWorkDocRows : XPLiteObject {
		int frow_id;
		[Key(true)]
		public int row_id {
			get { return frow_id; }
			set { SetPropertyValue<int>("row_id", ref frow_id, value); }
		}
		NET_SUTZ_MobileWorkUnit fParentID;
		[Indexed(Name=@"Index_ParentID")]
		[Association(@"NET_SUTZ_MobileWorkDocRowsReferencesNET_SUTZ_MobileWorkUnit")]
		public NET_SUTZ_MobileWorkUnit ParentID {
			get { return fParentID; }
			set { SetPropertyValue<NET_SUTZ_MobileWorkUnit>("ParentID", ref fParentID, value); }
		}
		Guid fDocLineGUID;
		[DisplayName(@"Идд строки документа")]
		public Guid DocLineGUID {
			get { return fDocLineGUID; }
			set { SetPropertyValue<Guid>("DocLineGUID", ref fDocLineGUID, value); }
		}
		int fLineNo;
		[DisplayName(@"Line No")]
		public int LineNo {
			get { return fLineNo; }
			set { SetPropertyValue<int>("LineNo", ref fLineNo, value); }
		}
	}

}
