//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.Exchange.SUTZ1C_SUTZNET {

		/// <summary>
		/// Выгружается единица задания на работу
		/// </summary>
	public partial class NET_SUTZ_MobileWorkUnit : XPLiteObject {
		int frow_id;
		[Key(true)]
		public int row_id {
			get { return frow_id; }
			set { SetPropertyValue<int>("row_id", ref frow_id, value); }
		}
		Guid fDocBaseID;
		public Guid DocBaseID {
			get { return fDocBaseID; }
			set { SetPropertyValue<Guid>("DocBaseID", ref fDocBaseID, value); }
		}
		Guid fJobeTypeID;
		/// <summary>
		/// Идентификатор элемента справочника СУТЗ "ОперацииСклада"
		/// </summary>
		[DisplayName(@"Операция склада")]
		public Guid JobeTypeID {
			get { return fJobeTypeID; }
			set { SetPropertyValue<Guid>("JobeTypeID", ref fJobeTypeID, value); }
		}
		DateTime fdTimeWrite;
		public DateTime dTimeWrite {
			get { return fdTimeWrite; }
			set { SetPropertyValue<DateTime>("dTimeWrite", ref fdTimeWrite, value); }
		}
		SUTZ_NET_HostsUsers fUserHostWriter;
		public SUTZ_NET_HostsUsers UserHostWriter {
			get { return fUserHostWriter; }
			set { SetPropertyValue<SUTZ_NET_HostsUsers>("UserHostWriter", ref fUserHostWriter, value); }
		}
		byte fis_read;
		[Indexed(Name=@"Index_IsRead")]
		public byte is_read {
			get { return fis_read; }
			set { SetPropertyValue<byte>("is_read", ref fis_read, value); }
		}
		DateTime? fdTimeRead;
		public DateTime? dTimeRead {
			get { return fdTimeRead; }
			set { SetPropertyValue<DateTime?>("dTimeRead", ref fdTimeRead, value); }
		}
		SUTZ_NET_HostsUsers fUserHostReader;
		public SUTZ_NET_HostsUsers UserHostReader {
			get { return fUserHostReader; }
			set { SetPropertyValue<SUTZ_NET_HostsUsers>("UserHostReader", ref fUserHostReader, value); }
		}
		bool fisMarkForDeleted;
		[DisplayName(@"Пометка удаления")]
		public bool isMarkForDeleted {
			get { return fisMarkForDeleted; }
			set { SetPropertyValue<bool>("isMarkForDeleted", ref fisMarkForDeleted, value); }
		}
		[Association(@"NET_SUTZ_MobileWorkDocRowsReferencesNET_SUTZ_MobileWorkUnit", typeof(NET_SUTZ_MobileWorkDocRows))]
		public XPCollection<NET_SUTZ_MobileWorkDocRows> NET_SUTZ_MobileWorkDocRows { get { return GetCollection<NET_SUTZ_MobileWorkDocRows>("NET_SUTZ_MobileWorkDocRows"); } }
		[Association(@"NET_SUTZ_MobileWorkUsersReferencesNET_SUTZ_MobileWorkUnit", typeof(NET_SUTZ_MobileWorkUsers))]
		public XPCollection<NET_SUTZ_MobileWorkUsers> NET_SUTZ_MobileWorkUsers { get { return GetCollection<NET_SUTZ_MobileWorkUsers>("NET_SUTZ_MobileWorkUsers"); } }
	}

}
