//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Exchange.SUTZ1C_SUTZNET.ndk_ecxhange_SUTZ_NET
{

    public partial class SUTZ_NET_OKEI : XPLiteObject
    {
        int frow_id;
        [Key(true)]
        public int row_id
        {
            get { return frow_id; }
            set { SetPropertyValue<int>("row_id", ref frow_id, value); }
        }
        Guid fiddSUTZ_guid;
        public Guid iddSUTZ_guid
        {
            get { return fiddSUTZ_guid; }
            set { SetPropertyValue<Guid>("iddSUTZ_guid", ref fiddSUTZ_guid, value); }
        }
        Guid fDelimeter;
        public Guid Delimeter
        {
            get { return fDelimeter; }
            set { SetPropertyValue<Guid>("Delimeter", ref fDelimeter, value); }
        }
        string fCode;
        [Size(16)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        Guid fParentID;
        public Guid ParentID
        {
            get { return fParentID; }
            set { SetPropertyValue<Guid>("ParentID", ref fParentID, value); }
        }
        DateTime fdTimeWrite;
        public DateTime dTimeWrite
        {
            get { return fdTimeWrite; }
            set { SetPropertyValue<DateTime>("dTimeWrite", ref fdTimeWrite, value); }
        }
        int fUserHostWriter;
        public int UserHostWriter
        {
            get { return fUserHostWriter; }
            set { SetPropertyValue<int>("UserHostWriter", ref fUserHostWriter, value); }
        }
        byte fis_read;
        public byte is_read
        {
            get { return fis_read; }
            set { SetPropertyValue<byte>("is_read", ref fis_read, value); }
        }
        DateTime fdTimeRead;
        public DateTime dTimeRead
        {
            get { return fdTimeRead; }
            set { SetPropertyValue<DateTime>("dTimeRead", ref fdTimeRead, value); }
        }
        int fUserHostReader;
        public int UserHostReader
        {
            get { return fUserHostReader; }
            set { SetPropertyValue<int>("UserHostReader", ref fUserHostReader, value); }
        }
    }

}
