//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Exchange.SUTZ1C_SUTZNET.ndk_ecxhange_SUTZ_NET
{

    public partial class SUTZ_NET_HostsUsers : XPLiteObject
    {
        int frow_id;
        [Key(true)]
        public int row_id
        {
            get { return frow_id; }
            set { SetPropertyValue<int>("row_id", ref frow_id, value); }
        }
        string fUserName;
        [Size(50)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        string fHostName;
        [Size(50)]
        public string HostName
        {
            get { return fHostName; }
            set { SetPropertyValue<string>("HostName", ref fHostName, value); }
        }
    }

}
