//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_023")]
		[System.ComponentModel.DefaultProperty("FullClassName")]
	public partial class MaxNumbersForObjects : XPBaseObject {
		string fidd;
		[Key]
		[Size(254)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public string idd {
			get { return fidd; }
			set { SetPropertyValue<string>("idd", ref fidd, value); }
		}
		string fPrefix;
		[Size(10)]
		[Persistent(@"f002")]
		[DisplayName(@"Префикс")]
		public string Prefix {
			get { return fPrefix; }
			set { SetPropertyValue<string>("Prefix", ref fPrefix, value); }
		}
		long fMaxNumber;
		[Persistent(@"f003")]
		[DisplayName(@"Макс.номер")]
		public long MaxNumber {
			get { return fMaxNumber; }
			set { SetPropertyValue<long>("MaxNumber", ref fMaxNumber, value); }
		}
		string fMaxFullCode;
		[Size(36)]
		[Persistent(@"f004")]
		[DisplayName(@"Макс.полный код")]
		public string MaxFullCode {
			get { return fMaxFullCode; }
			set { SetPropertyValue<string>("MaxFullCode", ref fMaxFullCode, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f005")]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		string fShortClassName;
		[Size(50)]
		[Persistent(@"f006")]
		[DisplayName(@"Короткое имя класса")]
		public string ShortClassName {
			get { return fShortClassName; }
			set { SetPropertyValue<string>("ShortClassName", ref fShortClassName, value); }
		}
		string fFullClassName;
		[Size(254)]
		[Persistent(@"f007")]
		[DisplayName(@"Полное имя класса")]
		public string FullClassName {
			get { return fFullClassName; }
			set { SetPropertyValue<string>("FullClassName", ref fFullClassName, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f008")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
