//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_004")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class UserSettings : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Users fParentID;
		[Persistent(@"f002")]
		[DisplayName(@"Владелец")]
		[Association(@"UserSettingsReferencesUsers")]
		public Users ParentID {
			get { return fParentID; }
			set { SetPropertyValue<Users>("ParentID", ref fParentID, value); }
		}
		JobTypes fJobType;
		[Persistent(@"f003")]
		[DisplayName(@"Вид работы")]
		public JobTypes JobType {
			get { return fJobType; }
			set { SetPropertyValue<JobTypes>("JobType", ref fJobType, value); }
		}
		string fDescription;
		[Persistent(@"f004")]
		[DisplayName(@"Наименование")]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
		SUTZ_2.Module.BO.References.Mobile.MobileWorkUnit fCurrentWorkUnit;
		[Persistent(@"f005")]
		[DisplayName(@"Текущий документ")]
		public SUTZ_2.Module.BO.References.Mobile.MobileWorkUnit CurrentWorkUnit {
			get { return fCurrentWorkUnit; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.Mobile.MobileWorkUnit>("CurrentWorkUnit", ref fCurrentWorkUnit, value); }
		}
		Guid fidGUID;
		[Persistent(@"f006")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"id guid")]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f007")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f008")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
