//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Indices(@"BaseDocument")]
	[Persistent(@"Table_027")]
		[System.ComponentModel.DefaultProperty("Barcode")]
	public partial class BarcodesOfShipments : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		SUTZ_2.Module.BO.Documents.BaseDocument fBaseDocument;
		[Indexed(@"Barcode", Name=@"Index_BaseDocumentBarcode", Unique=true)]
		[Persistent(@"f003")]
		[DisplayName(@"Документ")]
		public SUTZ_2.Module.BO.Documents.BaseDocument BaseDocument {
			get { return fBaseDocument; }
			set { SetPropertyValue<SUTZ_2.Module.BO.Documents.BaseDocument>("BaseDocument", ref fBaseDocument, value); }
		}
		Goods fGood;
		[Persistent(@"f004")]
		public Goods Good {
			get { return fGood; }
			set { SetPropertyValue<Goods>("Good", ref fGood, value); }
		}
		string fBarcode;
		[Size(128)]
		[Persistent(@"f005")]
		public string Barcode {
			get { return fBarcode; }
			set { SetPropertyValue<string>("Barcode", ref fBarcode, value); }
		}
		DateTime fDTimeScan;
		[Persistent(@"f007")]
		public DateTime DTimeScan {
			get { return fDTimeScan; }
			set { SetPropertyValue<DateTime>("DTimeScan", ref fDTimeScan, value); }
		}
		Users fUser;
		[Persistent(@"f006")]
		public Users User {
			get { return fUser; }
			set { SetPropertyValue<Users>("User", ref fUser, value); }
		}
		string fDocNumber;
		[Size(30)]
		[Persistent(@"f008")]
		public string DocNumber {
			get { return fDocNumber; }
			set { SetPropertyValue<string>("DocNumber", ref fDocNumber, value); }
		}
		Guid fidGUID;
		[Persistent(@"f009")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f010")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
