//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_009")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class Clients : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		string fCode;
		[Size(16)]
		[Persistent(@"f003")]
		[DisplayName(@"Код")]
		public string Code {
			get { return fCode; }
			set { SetPropertyValue<string>("Code", ref fCode, value); }
		}
		string fDescription;
		[Persistent(@"f004")]
		[DisplayName(@"Наименование")]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
		string fFullDescription;
		[Size(SizeAttribute.Unlimited)]
		[Persistent(@"f005")]
		[DisplayName(@"Полное наименование")]
		public string FullDescription {
			get { return fFullDescription; }
			set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
		}
		Guid fidGUID;
		[Persistent(@"f006")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		string fDeliveryAdress;
		[Persistent(@"f007")]
		[DisplayName(@"Адрес доставки")]
		public string DeliveryAdress {
			get { return fDeliveryAdress; }
			set { SetPropertyValue<string>("DeliveryAdress", ref fDeliveryAdress, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f008")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
		[Association(@"ClientDivisionsReferencesClients", typeof(ClientDivisions)), Aggregated]
		public XPCollection<ClientDivisions> ClientDivisionsCollection { get { return GetCollection<ClientDivisions>("ClientDivisionsCollection"); } }
		[Association(@"ClientShopsReferencesClients", typeof(ClientShops)), Aggregated]
		public XPCollection<ClientShops> ClientShopsCollection { get { return GetCollection<ClientShops>("ClientShopsCollection"); } }
	}

}
