//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_011")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class Delimeters : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		string fDescription;
		[Persistent(@"f002")]
		[DisplayName(@"Наименование")]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
		Guid fDelimeterID;
		[Persistent(@"f003")]
		public Guid DelimeterID {
			get { return fDelimeterID; }
			set { SetPropertyValue<Guid>("DelimeterID", ref fDelimeterID, value); }
		}
		bool fDefaultDelimeter;
		[Persistent(@"f004")]
		[DisplayName(@"Разделитель по умолчанию")]
		public bool DefaultDelimeter {
			get { return fDefaultDelimeter; }
			set { SetPropertyValue<bool>("DefaultDelimeter", ref fDefaultDelimeter, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f005")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
