//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_008")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class PropertiesOfGoods : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		Goods fParentId;
		[Persistent(@"f003")]
		[DisplayName(@"Владелец")]
		[Association(@"PropertiesOfGoodsReferencesGoods")]
		public Goods ParentId {
			get { return fParentId; }
			set { SetPropertyValue<Goods>("ParentId", ref fParentId, value); }
		}
		string fCode;
		[Size(16)]
		[Persistent(@"f004")]
		[DisplayName(@"Код")]
		public string Code {
			get { return fCode; }
			set { SetPropertyValue<string>("Code", ref fCode, value); }
		}
		string fDescription;
		[Size(50)]
		[Persistent(@"f005")]
		[DisplayName(@"Наименование")]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
		DateTime? fProductionDate;
		[Persistent(@"f006")]
		[DisplayName(@"Дата производства")]
		public DateTime? ProductionDate {
			get { return fProductionDate; }
			set { SetPropertyValue<DateTime?>("ProductionDate", ref fProductionDate, value); }
		}
		DateTime? fExpirationDate;
		[Persistent(@"f007")]
		[DisplayName(@"Срок годности")]
		public DateTime? ExpirationDate {
			get { return fExpirationDate; }
			set { SetPropertyValue<DateTime?>("ExpirationDate", ref fExpirationDate, value); }
		}
		short fPackKoeff;
		[Persistent(@"f008")]
		[DisplayName(@"Коэффициент")]
		public short PackKoeff {
			get { return fPackKoeff; }
			set { SetPropertyValue<short>("PackKoeff", ref fPackKoeff, value); }
		}
		string fComment;
		[Size(50)]
		[Persistent(@"f009")]
		[DisplayName(@"Комментарий")]
		public string Comment {
			get { return fComment; }
			set { SetPropertyValue<string>("Comment", ref fComment, value); }
		}
		Guid fidGUID;
		[Persistent(@"f010")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f011")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
