//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_007")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class SetOfGoods : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		Goods fParentId;
		[Persistent(@"f003")]
		[DisplayName(@"Владелец")]
		[Association(@"SetOfGoodsReferencesGoods")]
		public Goods ParentId {
			get { return fParentId; }
			set { SetPropertyValue<Goods>("ParentId", ref fParentId, value); }
		}
		Goods fGood;
		[Persistent(@"f004")]
		[DisplayName(@"Товар")]
		public Goods Good {
			get { return fGood; }
			set { SetPropertyValue<Goods>("Good", ref fGood, value); }
		}
		Units fUnit;
		[Persistent(@"f005")]
		[DevExpress.Persistent.Base.DataSourceProperty("ParentId.UnitsCollection")]
		[DisplayName(@"Ед.Измерения")]
		public Units Unit {
			get { return fUnit; }
			set { SetPropertyValue<Units>("Unit", ref fUnit, value); }
		}
		int fQuantity;
		[Persistent(@"f006")]
		[DisplayName(@"Количество")]
		public int Quantity {
			get { return fQuantity; }
			set { SetPropertyValue<int>("Quantity", ref fQuantity, value); }
		}
		Guid fidGUID;
		[Persistent(@"f007")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"id guid")]
			[MergeCollisionBehavior(OptimisticLockingReadMergeBehavior.Ignore)]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f008")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
