//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References {

	[Persistent(@"Table_014")]
		[System.ComponentModel.DefaultProperty("Description")]
	public partial class StockRooms : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		string fCode;
		[Size(16)]
		[Persistent(@"f003")]
		[DisplayName(@"Код")]
		public string Code {
			get { return fCode; }
			set { SetPropertyValue<string>("Code", ref fCode, value); }
		}
		string fDescription;
		[Size(50)]
		[Persistent(@"f004")]
		[DisplayName(@"Наименование")]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
		SUTZ_2.Module.BO.enTypeOfStockRooms fTypeOfStockRoom;
		[Persistent(@"f005")]
		[DisplayName(@"Тип кладовой")]
		public SUTZ_2.Module.BO.enTypeOfStockRooms TypeOfStockRoom {
			get { return fTypeOfStockRoom; }
			set { SetPropertyValue<SUTZ_2.Module.BO.enTypeOfStockRooms>("TypeOfStockRoom", ref fTypeOfStockRoom, value); }
		}
		Guid fidGUID;
		[Persistent(@"f006")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		bool fisGroupOfStockRooms;
		[Persistent(@"f007")]
		[DisplayName(@"Это группа")]
		public bool isGroupOfStockRooms {
			get { return fisGroupOfStockRooms; }
			set { SetPropertyValue<bool>("isGroupOfStockRooms", ref fisGroupOfStockRooms, value); }
		}
		string fLogisticParameter;
		[Persistent(@"f008")]
		[DisplayName(@"Логистический параметр")]
		public string LogisticParameter {
			get { return fLogisticParameter; }
			set { SetPropertyValue<string>("LogisticParameter", ref fLogisticParameter, value); }
		}
		bool fRemoveFromMixing;
		[Persistent(@"f009")]
		[DisplayName(@"Удалить из смешивания")]
		public bool RemoveFromMixing {
			get { return fRemoveFromMixing; }
			set { SetPropertyValue<bool>("RemoveFromMixing", ref fRemoveFromMixing, value); }
		}
		Warehouses fWarehouse;
		[Persistent(@"f010")]
		[DisplayName(@"Склад АСУ")]
		public Warehouses Warehouse {
			get { return fWarehouse; }
			set { SetPropertyValue<Warehouses>("Warehouse", ref fWarehouse, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f011")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
