//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SUTZ_2.Module.BO.Documents
{

    [Persistent(@"Table_110")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class DocTrebovanie : BaseDocument
    {
        bool fAllowMovement;
        [Persistent(@"f050")]
        [DevExpress.Xpo.DisplayName(@"РазрешитьДвижение")]
        public bool AllowMovement
        {
            get { return fAllowMovement; }
            set { SetPropertyValue<bool>("AllowMovement", ref fAllowMovement, value); }
        }
        [Association(@"DocTrebovanieGoodsReferencesDocTrebovanie"), Aggregated]
        public XPCollection<DocTrebovanieGoods> DocTrebovanieGoodsCollection { get { return GetCollection<DocTrebovanieGoods>("DocTrebovanieGoodsCollection"); } }
    }

}
