//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References.Mobile {

		/// <summary>
		/// Аналог справочника СУТЗ свойства документа. В этом классе будет храниться значения разный свойств для пары Документ-ВидРаботы.
		/// </summary>
	[Persistent(@"Table_034")]
		[DevExpress.Persistent.Validation.RuleCombinationOfPropertiesIsUnique("UniqueRuleForDocProperties", DevExpress.Persistent.Validation.DefaultContexts.Save,"BaseDoc,JobType")]
	public partial class DocJobesProperties : XPBaseObject {
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		int fidd;
		[PersistentAlias("fidd")]
		public int idd {
			get { return fidd; }
		}
		SUTZ_2.Module.BO.Documents.BaseDocument fBaseDoc;
		[Persistent(@"f002")]
		[DisplayName(@"Документ")]
		public SUTZ_2.Module.BO.Documents.BaseDocument BaseDoc {
			get { return fBaseDoc; }
			set { SetPropertyValue<SUTZ_2.Module.BO.Documents.BaseDocument>("BaseDoc", ref fBaseDoc, value); }
		}
		SUTZ_2.Module.BO.References.Delimeters fDelimeter;
		[Persistent(@"f003")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public SUTZ_2.Module.BO.References.Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		SUTZ_2.Module.BO.References.JobTypes fJobType;
		/// <summary>
		/// Вид работы, присвоенный единице работы
		/// </summary>
		[Persistent(@"f004")]
		[DisplayName(@"Вид работы")]
		public SUTZ_2.Module.BO.References.JobTypes JobType {
			get { return fJobType; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.JobTypes>("JobType", ref fJobType, value); }
		}
		SUTZ_2.Module.BO.enTypesOfMobileStates fTypeOfMobileState;
		/// <summary>
		/// Состояние работы в целом по документу, определяет доступность работы по выбранному документу для работ по моб.сутз
		/// </summary>
		[Persistent(@"f005")]
		[DisplayName(@"Состояние задания")]
		public SUTZ_2.Module.BO.enTypesOfMobileStates TypeOfMobileState {
			get { return fTypeOfMobileState; }
			set { SetPropertyValue<SUTZ_2.Module.BO.enTypesOfMobileStates>("TypeOfMobileState", ref fTypeOfMobileState, value); }
		}
		Guid fidGUID;
		[Persistent(@"f006")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"IDD SUTZ")]
		public Guid idGUID {
			get { return fidGUID; }
			set { SetPropertyValue<Guid>("idGUID", ref fidGUID, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f007")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
