//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.References.Mobile {

	[Persistent(@"Table_031")]
	public partial class MobileWorkUsers : XPBaseObject {
		int fidd;
		[Key(true)]
		[Persistent(@"f001")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		public int idd {
			get { return fidd; }
			set { SetPropertyValue<int>("idd", ref fidd, value); }
		}
		SUTZ_2.Module.BO.References.Delimeters fDelimeter;
		[Persistent(@"f002")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Разделитель")]
		public SUTZ_2.Module.BO.References.Delimeters Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.Delimeters>("Delimeter", ref fDelimeter, value); }
		}
		MobileWorkUnit fParentId;
		[Persistent(@"f003")]
		[DisplayName(@"единица работы")]
		[Association(@"MobileWorkUsersReferencesMobileWorkUnit")]
		public MobileWorkUnit ParentId {
			get { return fParentId; }
			set { SetPropertyValue<MobileWorkUnit>("ParentId", ref fParentId, value); }
		}
		SUTZ_2.Module.BO.References.Users fUser;
		[Persistent(@"f004")]
		[DisplayName(@"Пользователь")]
		public SUTZ_2.Module.BO.References.Users User {
			get { return fUser; }
			set { SetPropertyValue<SUTZ_2.Module.BO.References.Users>("User", ref fUser, value); }
		}
		MobileErrors fErrorState;
		/// <summary>
		/// Ошибка, указанная пользователем во время выполнения операции
		/// </summary>
		[Persistent(@"f005")]
		public MobileErrors ErrorState {
			get { return fErrorState; }
			set { SetPropertyValue<MobileErrors>("ErrorState", ref fErrorState, value); }
		}
		DateTime fdTimeStart;
		[Persistent(@"f006")]
		[DisplayName(@"Время начала")]
		public DateTime dTimeStart {
			get { return fdTimeStart; }
			set { SetPropertyValue<DateTime>("dTimeStart", ref fdTimeStart, value); }
		}
		DateTime fdTimeEnd;
		[Persistent(@"f007")]
		[DisplayName(@"Время завершения")]
		public DateTime dTimeEnd {
			get { return fdTimeEnd; }
			set { SetPropertyValue<DateTime>("dTimeEnd", ref fdTimeEnd, value); }
		}
		DateTime? fdTimeClosedFrom;
		[Persistent(@"f008")]
		[DisplayName(@"Время сканирования ВзятьИз")]
		public DateTime? dTimeClosedFrom {
			get { return fdTimeClosedFrom; }
			set { SetPropertyValue<DateTime?>("dTimeClosedFrom", ref fdTimeClosedFrom, value); }
		}
		DateTime? fdTimeClosedTo;
		[Persistent(@"f009")]
		[DisplayName(@"Время сканирования ПоложитьВ")]
		public DateTime? dTimeClosedTo {
			get { return fdTimeClosedTo; }
			set { SetPropertyValue<DateTime?>("dTimeClosedTo", ref fdTimeClosedTo, value); }
		}
		bool fIsMarkDeleted;
		[Persistent(@"f011")]
		[DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false), DevExpress.Persistent.Base.VisibleInLookupListView(false)]
		[DisplayName(@"Пометка удаления")]
		public bool IsMarkDeleted {
			get { return fIsMarkDeleted; }
			set { SetPropertyValue<bool>("IsMarkDeleted", ref fIsMarkDeleted, value); }
		}
	}

}
