//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.Exchange.SUTZ1C_SUTZNET {

	public partial class SUTZ_NET_DocTrebovanieGoods : XPLiteObject {
		int frow_id;
		[Key(true)]
		public int row_id {
			get { return frow_id; }
			set { SetPropertyValue<int>("row_id", ref frow_id, value); }
		}
		SUTZ_NET_DocTrebovanieHeaders fHeaderID;
		[Indexed(Name=@"Index_HeaderID")]
		[Association(@"SUTZ_NET_DocTrebovanieGoodsReferencesSUTZ_NET_DocTrebovanieHeaders")]
		public SUTZ_NET_DocTrebovanieHeaders HeaderID {
			get { return fHeaderID; }
			set { SetPropertyValue<SUTZ_NET_DocTrebovanieHeaders>("HeaderID", ref fHeaderID, value); }
		}
		int fDocLineNo;
		public int DocLineNo {
			get { return fDocLineNo; }
			set { SetPropertyValue<int>("DocLineNo", ref fDocLineNo, value); }
		}
		Guid fGoodID;
		public Guid GoodID {
			get { return fGoodID; }
			set { SetPropertyValue<Guid>("GoodID", ref fGoodID, value); }
		}
		Guid fUnitID;
		public Guid UnitID {
			get { return fUnitID; }
			set { SetPropertyValue<Guid>("UnitID", ref fUnitID, value); }
		}
		decimal fQuantityOfUnits;
		public decimal QuantityOfUnits {
			get { return fQuantityOfUnits; }
			set { SetPropertyValue<decimal>("QuantityOfUnits", ref fQuantityOfUnits, value); }
		}
		decimal fTotalQuantity;
		public decimal TotalQuantity {
			get { return fTotalQuantity; }
			set { SetPropertyValue<decimal>("TotalQuantity", ref fTotalQuantity, value); }
		}
		DateTime? fBestBefore;
		public DateTime? BestBefore {
			get { return fBestBefore; }
			set { SetPropertyValue<DateTime?>("BestBefore", ref fBestBefore, value); }
		}
		Guid fPropertyID;
		public Guid PropertyID {
			get { return fPropertyID; }
			set { SetPropertyValue<Guid>("PropertyID", ref fPropertyID, value); }
		}
		Guid fDocLineUID;
		public Guid DocLineUID {
			get { return fDocLineUID; }
			set { SetPropertyValue<Guid>("DocLineUID", ref fDocLineUID, value); }
		}
	}

}
