//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace SUTZ_2.Module.BO.Exchange.SUTZ1C_SUTZNET {

	public partial class SUTZ_NET_DocProperties : XPLiteObject {
		int frow_id;
		[Key(true)]
		public int row_id {
			get { return frow_id; }
			set { SetPropertyValue<int>("row_id", ref frow_id, value); }
		}
		Guid fiddSUTZ_GUID;
		/// <summary>
		/// Идентификатор документа в СУТЗ
		/// </summary>
		public Guid iddSUTZ_GUID {
			get { return fiddSUTZ_GUID; }
			set { SetPropertyValue<Guid>("iddSUTZ_GUID", ref fiddSUTZ_GUID, value); }
		}
		Guid fDocBaseID;
		[DisplayName(@"Идентификатор документа")]
		public Guid DocBaseID {
			get { return fDocBaseID; }
			set { SetPropertyValue<Guid>("DocBaseID", ref fDocBaseID, value); }
		}
		short fSign1;
		/// <summary>
		/// Первый знак
		/// </summary>
		[DisplayName(@"Первый знак")]
		public short Sign1 {
			get { return fSign1; }
			set { SetPropertyValue<short>("Sign1", ref fSign1, value); }
		}
		short fSign2;
		/// <summary>
		/// Второй знак
		/// </summary>
		[DisplayName(@"Второй знак")]
		public short Sign2 {
			get { return fSign2; }
			set { SetPropertyValue<short>("Sign2", ref fSign2, value); }
		}
		short fSign3;
		/// <summary>
		/// Третий знак
		/// </summary>
		[DisplayName(@"Третий знак")]
		public short Sign3 {
			get { return fSign3; }
			set { SetPropertyValue<short>("Sign3", ref fSign3, value); }
		}
		short fSign4;
		/// <summary>
		/// Четвертый знак
		/// </summary>
		[DisplayName(@"Четвертый знак")]
		public short Sign4 {
			get { return fSign4; }
			set { SetPropertyValue<short>("Sign4", ref fSign4, value); }
		}
		DateTime fdTimeWrite;
		public DateTime dTimeWrite {
			get { return fdTimeWrite; }
			set { SetPropertyValue<DateTime>("dTimeWrite", ref fdTimeWrite, value); }
		}
		SUTZ_NET_HostsUsers fUserHostWriter;
		public SUTZ_NET_HostsUsers UserHostWriter {
			get { return fUserHostWriter; }
			set { SetPropertyValue<SUTZ_NET_HostsUsers>("UserHostWriter", ref fUserHostWriter, value); }
		}
		byte fis_read;
		[Indexed(Name=@"Index_IsRead")]
		public byte is_read {
			get { return fis_read; }
			set { SetPropertyValue<byte>("is_read", ref fis_read, value); }
		}
		DateTime? fdTimeRead;
		public DateTime? dTimeRead {
			get { return fdTimeRead; }
			set { SetPropertyValue<DateTime?>("dTimeRead", ref fdTimeRead, value); }
		}
		SUTZ_NET_HostsUsers fUserHostReader;
		public SUTZ_NET_HostsUsers UserHostReader {
			get { return fUserHostReader; }
			set { SetPropertyValue<SUTZ_NET_HostsUsers>("UserHostReader", ref fUserHostReader, value); }
		}
		Guid fDelimeter;
		public Guid Delimeter {
			get { return fDelimeter; }
			set { SetPropertyValue<Guid>("Delimeter", ref fDelimeter, value); }
		}
		bool fisMarkForDeleted;
		[DisplayName(@"Пометка удаления")]
		public bool isMarkForDeleted {
			get { return fisMarkForDeleted; }
			set { SetPropertyValue<bool>("isMarkForDeleted", ref fisMarkForDeleted, value); }
		}
	}

}
